"""Emit the conformance fixture the Kotlin core is tested against.

Two parts, both regenerable and both consumed by
platforms/android/core/src/test/kotlin/.../ConformanceTest.kt:

1. A deterministic 12 s signal (defined by formula, so both implementations
   regenerate it bit-for-bit rather than reading audio files): per 100 ms
   block, the Python core's dBFS, spectral flatness, short-term LUFS,
   loudness confidence and 12-bit chroma signature.
2. A scripted vote sequence replayed through Fusion + AdStateMachine: per
   tick, the combined confidence, mute side, state and action.

Run from the repo root: python tools/gen_conformance.py
"""

from __future__ import annotations

import math
from pathlib import Path

import numpy as np

from adhush.config import FusionConfig, LoudnessConfig
from adhush.detect.fusion import Fusion
from adhush.detect.loudness import LoudnessDetector
from adhush.detect.silence import block_dbfs, spectral_flatness
from adhush.events import AudioEvent, DetectorVote, MuteDecision
from adhush.fingerprint.audio_chroma import chroma_bits
from adhush.state import AdStateMachine

RATE = 48_000
BLOCK = 4_800  # 100 ms
BLOCKS = 120  # 12 s
OUT = Path("platforms/android/core/src/test/resources/conformance.txt")


def block_samples(index: int) -> np.ndarray:
    """The shared signal. Kotlin's ConformanceTest.signal() must match this exactly."""
    n = np.arange(index * BLOCK, (index + 1) * BLOCK, dtype=np.float64)
    t = n / RATE
    x = 0.05 * np.sin(2 * math.pi * 220.0 * t) + 0.03 * np.sin(2 * math.pi * 440.0 * t)
    x += 0.02 * np.sin(2 * math.pi * 1000.0 * t)
    if 60 <= index < 90:  # "the ad": +12 dB and a bright component
        x = 4.0 * x + 0.02 * np.sin(2 * math.pi * 3000.0 * t)
    if 40 <= index < 45:  # a pod-boundary gap
        x = np.zeros_like(x)
    return x.astype(np.float32)


def main() -> None:
    lines = ["# generated by tools/gen_conformance.py — do not edit"]
    loud = LoudnessDetector(LoudnessConfig())
    for i in range(BLOCKS):
        samples = block_samples(i)
        ts = i * BLOCK / RATE
        loud.observe_audio(AudioEvent(ts=ts, samples=samples, sample_rate=RATE))
        vote = loud.vote(ts)
        lines.append(
            "block {i} {ts!r} {dbfs:.9f} {flat:.12f} {st:.9f} {conf:.9f} {chroma}".format(
                i=i,
                ts=ts,
                dbfs=block_dbfs(samples),
                flat=spectral_flatness(samples),
                st=loud._last_short_term,
                conf=vote.confidence,
                chroma=chroma_bits(samples, RATE),
            )
        )

    weights = {"a": 0.15, "b": 0.15, "c": 0.30}
    fusion = Fusion(FusionConfig(), weights, ["a", "b", "c"])
    machine = AdStateMachine(FusionConfig())
    # (a, b, c, promote, fp_hold) per 100 ms tick: program, a two-detector ad
    # with a decaying boundary signal, a fingerprint promotion, a long hold.
    script: list[tuple[float, float, float, bool, bool]] = []
    script += [(0.0, 0.0, 0.0, False, False)] * 10
    script += [(1.0, 0.9, 0.0, False, False)] * 12  # both agree -> mute after dwell
    script += [(1.0 - 0.1 * k, 0.9, 0.0, False, False) for k in range(10)]  # a fades
    script += [(0.0, 0.9, 0.0, False, False)] * 5  # b alone holds the mute
    script += [(0.0, 0.0, 0.0, False, False)] * 10  # program -> unmute after dwell
    script += [(0.0, 0.0, 0.0, False, False)] * 25  # recovery, then quiet
    script += [(0.0, 0.0, 1.0, True, True)] * 3  # fingerprint: promote instantly
    script += [(0.0, 0.0, 1.0, False, True)] * 30  # hold inside the learned window
    script += [(0.0, 0.0, 0.0, False, False)] * 12  # window over -> unmute by dwell
    lines.append(f"weights a=0.15 b=0.15 c=0.30")
    for i, (a, b, c, promote, hold) in enumerate(script):
        ts = i * 0.1
        votes = [
            DetectorVote("a", ts, a, "x"),
            DetectorVote("b", ts, b, "x"),
            DetectorVote("c", ts, c, "x"),
        ]
        decision: MuteDecision = fusion.combine(votes, ts)
        action = machine.update(decision, promote=promote, fp_hold=hold, program_evidence=False)
        lines.append(
            f"tick {i} {ts!r} {a:.3f} {b:.3f} {c:.3f} {int(promote)} {int(hold)} "
            f"{int(decision.mute)} {decision.confidence:.12f} {machine.state.value} "
            f"{action.value if action else '-'}"
        )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
